In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("customer.csv")

In [6]:
df.sample(3)

    age gender   review education purchased
28   48   Male     Poor    School        No
32   92   Male  Average        UG       Yes
16   59   Male     Poor        UG       Yes

From the above dataset preview one can say that , gender (nominal) , review (ordinal) ,education (ordinal) and purchased (nominal) are all categorical cols.

o/p col is also categorical -> Classification problem

In [8]:
df = df.iloc[:,2:]

In [9]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [40]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,0:2] , df.iloc[:,:-1] , test_size=0.2)

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
X_train

     review education
45     Poor        PG
2      Good        PG
42     Good        PG
14     Poor        PG
49     Good        UG
21  Average        PG
28     Poor    School
48     Good        UG
34  Average    School
6      Good    School
24  Average        PG
4   Average        UG
7      Poor    School
43     Poor        PG
32  Average        UG
16     Poor        UG
19     Poor        PG
5   Average    School
13  Average    School
1      Poor        UG
10     Good        UG
30  Average        UG
33     Good        PG
12     Poor    School
9      Good        UG
27     Poor        PG
8   Average        UG
25     Good    School
15     Poor        UG
29  Average        UG
39     Poor        PG
18     Good    School
44  Average        UG
36     Good        UG
47     Good        PG
31     Poor    School
23     Good    School
20  Average    School
11     Good        UG
40     Good    School

In [44]:
y_train

     review education
38     Good    School
43     Poor        PG
10     Good        UG
1      Poor        UG
35     Poor    School
13  Average    School
34  Average    School
21  Average        PG
17     Poor        UG
29  Average        UG
46     Poor        PG
5   Average    School
23     Good    School
28     Poor    School
31     Poor    School
20  Average    School
6      Good    School
27     Poor        PG
26     Poor        PG
24  Average        PG
19     Poor        PG
22     Poor        PG
8   Average        UG
36     Good        UG
11     Good        UG
12     Poor    School
18     Good    School
7      Poor    School
40     Good    School
49     Good        UG
32  Average        UG
16     Poor        UG
44  Average        UG
3      Good        PG
2      Good        PG
48     Good        UG
15     Poor        UG
39     Poor        PG
30  Average        UG
41     Good        PG

In [18]:
# object of ordinal encoder class
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [19]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [20]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [21]:
X_train

array([[0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [2., 0.]])

In [25]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

## Label Encoding

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le = LabelEncoder()

In [28]:
le.fit(y_train[:,''])

ValueError: y should be a 1d array, got an array of shape (40, 2) instead.

In [29]:
y_train

     review education
45     Poor        PG
2      Good        PG
42     Good        PG
14     Poor        PG
49     Good        UG
21  Average        PG
28     Poor    School
48     Good        UG
34  Average    School
6      Good    School
24  Average        PG
4   Average        UG
7      Poor    School
43     Poor        PG
32  Average        UG
16     Poor        UG
19     Poor        PG
5   Average    School
13  Average    School
1      Poor        UG
10     Good        UG
30  Average        UG
33     Good        PG
12     Poor    School
9      Good        UG
27     Poor        PG
8   Average        UG
25     Good    School
15     Poor        UG
29  Average        UG
39     Poor        PG
18     Good    School
44  Average        UG
36     Good        UG
47     Good        PG
31     Poor    School
23     Good    School
20  Average    School
11     Good        UG
40     Good    School

Label encoding to be redone once you learn Scikit learn as the train test split fn is not 
allocating y_train a single col