## Binarization

In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score

In [8]:
df = pd.read_csv('train.csv')[['Age' , 'Fare' , 'SibSp' ,  'Parch' , 'Survived']]

In [9]:
df.dropna(inplace=True)

In [10]:
df.shape

(714, 5)

In [11]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [12]:
df['Family'] = df['SibSp'] + df['Parch']
df.head()

    Age     Fare  SibSp  Parch  Survived  Family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [13]:
df.drop(columns=['SibSp' , 'Parch'])

      Age     Fare  Survived  Family
0    22.0   7.2500         0       1
1    38.0  71.2833         1       1
2    26.0   7.9250         1       0
3    35.0  53.1000         1       1
4    35.0   8.0500         0       0
..    ...      ...       ...     ...
885  39.0  29.1250         0       5
886  27.0  13.0000         0       0
887  19.0  30.0000         1       0
889  26.0  30.0000         1       0
890  32.0   7.7500         0       0

[714 rows x 4 columns]

In [15]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [16]:
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state=42 , test_size=0.2)

In [17]:
X_train.head()

      Age     Fare  SibSp  Parch  Family
328  31.0  20.5250      1      1       2
73   26.0  14.4542      1      0       1
253  30.0  16.1000      1      0       1
719  33.0   7.7750      0      0       0
666  25.0  13.0000      0      0       0

In [18]:
# Without Binarization 

clf = DecisionTreeClassifier()
clf.fit(X_train , y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test , y_pred)

0.6433566433566433

In [19]:
np.mean(cross_val_score(DecisionTreeClassifier() , X , y , cv=10 , scoring='accuracy'))

np.float64(0.6512910798122066)

In [21]:
# Applying Binarization

from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import KBinsDiscretizer

In [22]:
k_bin_age = KBinsDiscretizer(n_bins=15 , strategy='quantile' , encode='ordinal')
k_bin_fare = KBinsDiscretizer(n_bins=15 , strategy='quantile' , encode='ordinal')

In [25]:
trf = ColumnTransformer([
    ('first' , k_bin_age , [0]),
    ('second' , k_bin_fare , [1])
])

In [27]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

C:\Users\rishi\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\rishi\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [29]:
trf.named_transformers_['first'].n_bins_

array([15])