In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Workig with dates

In [8]:
# cnvet to date time data type
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. extract year

In [10]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
485 2019-10-11        6941       30       1       2019
994 2018-10-23         785       16       1       2018
763 2018-11-25        1467       22      90       2018
439 2019-11-21        7224       25       1       2019
380 2019-08-10        1005       14       1       2019

### 2. extract months

In [15]:
date['month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  month_no
0 2019-12-10        5628       25       3       2019        12
1 2018-08-15        3646       14     157       2018         8
2 2018-10-23        1859       25       1       2018        10
3 2019-08-17        7292       25       1       2019         8
4 2019-01-06        4344       25       3       2019         1

In [17]:
date['month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year  month_no month_name
0 2019-12-10        5628       25       3       2019        12   December
1 2018-08-15        3646       14     157       2018         8     August
2 2018-10-23        1859       25       1       2018        10    October
3 2019-08-17        7292       25       1       2019         8     August
4 2019-01-06        4344       25       3       2019         1    January

In [21]:
date['date_day'] = date['date'].dt.day
date['dow'] = date['date'].dt.dayofweek
date['dow_name'] = date['date'].dt.day_name()

date.head()

,date,product_id,city_id,orders,date_year,month_no,month_name,date_day,dow,dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [23]:
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  month_no month_name  date_day  dow   dow_name
0 2019-12-10       2019        12   December        10    1    Tuesday
1 2018-08-15       2018         8     August        15    2  Wednesday
2 2018-10-23       2018        10    October        23    1    Tuesday
3 2019-08-17       2019         8     August        17    5   Saturday
4 2019-01-06       2019         1    January         6    6     Sunday

## extract time elapsed between dates

In [26]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 30, 23, 12, 3, 820152)

In [28]:
today - date['date']

0     2424 days 23:12:03.820152
1     2906 days 23:12:03.820152
2     2837 days 23:12:03.820152
3     2539 days 23:12:03.820152
4     2762 days 23:12:03.820152
                 ...
995   2852 days 23:12:03.820152
996   2793 days 23:12:03.820152
997   2641 days 23:12:03.820152
998   2706 days 23:12:03.820152
999   2480 days 23:12:03.820152
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
(today - date['date']).dt.days

0      2424
1      2906
2      2837
3      2539
4      2762
       ...
995    2852
996    2793
997    2641
998    2706
999    2480
Name: date, Length: 1000, dtype: int64

In [32]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [34]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [36]:
time['date'] = pd.to_datetime(time['date'])

In [38]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [41]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0
...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,0,50,0
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23,14,0
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23,37,0
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23,34,0
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23,25,0

In [43]:
time.drop(columns=['msg'])

                   date  hour  min  sec
0   2013-12-15 00:50:00     0   50    0
1   2014-04-29 23:40:00    23   40    0
2   2012-12-30 00:21:00     0   21    0
3   2014-11-28 00:31:00     0   31    0
4   2013-10-26 23:11:00    23   11    0
..                  ...   ...  ...  ...
995 2012-03-16 00:50:00     0   50    0
996 2014-01-23 23:14:00    23   14    0
997 2012-10-15 23:37:00    23   37    0
998 2012-06-21 23:34:00    23   34    0
999 2014-06-19 23:25:00    23   25    0

[1000 rows x 4 columns]

In [45]:
today - time['date']

0     4610 days 22:22:03.820152
1     4474 days 23:32:03.820152
2     4960 days 22:51:03.820152
3     4262 days 22:41:03.820152
4     4660 days 00:01:03.820152
                 ...
995   5249 days 22:22:03.820152
996   4570 days 23:58:03.820152
997   5035 days 23:35:03.820152
998   5151 days 23:38:03.820152
999   4423 days 23:47:03.820152
Name: date, Length: 1000, dtype: timedelta64[ns]